name: Deploy to Render

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:latest ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:$(git rev-parse --short HEAD)

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:$(git rev-parse --short HEAD)

  deploy-to-render:
    name: Deploy to Render
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'
