name: CI/CD Pipeline - Docker + Render

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  tests:
    name: Lint, Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests and collect coverage
        run: |
          pytest --ds=oc_lettings_site.settings --cov=. --cov-report=term --cov-fail-under=80

  docker:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & tag image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:latest .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/python-oc-lettings:latest

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Trigger Render Deploy via Deploy Hook
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
