name: CI/CD Pipeline - Render auto-deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-test:
    name: Lint, Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 coverage

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest --ds=oc_lettings_site.settings
          coverage report -m
          coverage xml

  deploy:
    name: Trigger Render deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Call Render deploy hook
        run: |
          curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
